services:
  db:
    ports:
      - 5439:5432
  webapp-registry:
    environment:
      API_URL: https://ferriskey.tail6af481.ts.net
  api-registry:
    environment:
      WEBAPP_URL: https://ferriskey.tail6af481.ts.net
      ALLOWED_ORIGINS: https://ferriskey.tail6af481.ts.net
      ACTIVE_OBSERVABILITY: "true"
      OTLP_ENDPOINT: "http://host.docker.internal:17011"
      METRICS_ENDPOINT: "http://host.docker.internal:17011"
      OTLP_PROTOCOL: "http"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  webapp-build:
    environment:
      API_URL: https://ferriskey.tail6af481.ts.net
  api-build:
    environment:
      WEBAPP_URL: https://ferriskey.tail6af481.ts.net
      ALLOWED_ORIGINS: https://ferriskey.tail6af481.ts.net
      ACTIVE_OBSERVABILITY: "true"
      OTLP_ENDPOINT: "http://host.docker.internal:17011"
      METRICS_ENDPOINT: "http://host.docker.internal:17011"
      OTLP_PROTOCOL: "http"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  tailscale-proxy:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      api-build:
        condition: service_healthy
        required: false
      webapp-build:
        condition: service_healthy
        required: false
    volumes:
      - ./nginx.tailscale.conf:/etc/nginx/conf.d/default.conf:ro
